# Generated by Django 2.2.5 on 2019-09-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_works', to='works.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('identifier', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswc', models.CharField(blank=True, default='', max_length=11, unique=True)),
                ('id_from_source', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('contributors', models.ManyToManyField(related_name='works', through='works.ContributorWork', to='works.Contributor')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='works.Source')),
            ],
            options={
                'unique_together': {('source', 'id_from_source')},
            },
        ),
        migrations.AddField(
            model_name='contributorwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_works', to='works.Work'),
        ),
        migrations.AlterUniqueTogether(
            name='contributorwork',
            unique_together={('contributor', 'work')},
        ),
    ]
