# Generated by Django 2.2.5 on 2019-09-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
