# Generated by Django 2.2.5 on 2019-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20190914_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
