# Generated by Django 2.2.5 on 2019-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20190915_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='iswc',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
