# Generated by Django 2.2.5 on 2019-09-15 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20190915_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title_synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=[], size=None),
        ),
    ]
