# Generated by Django 2.2.5 on 2019-09-15 13:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_work_title_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title_synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
    ]
