# Generated by Django 2.2.5 on 2019-09-15 14:37

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20190915_1352'),
    ]

    operations = [
        CITextExtension(),
    ]
